"""
把 Python 端 RecipeBook 34 配方 dump 成 GDScript 端可消费的 const 数组。
生成 core/abstract/crafting/recipe_book_data.gd(被 crafting_demo.gd 引用)。

用法:
  python3 core/abstract/crafting/_dump_recipes.py
  # 输出: core/abstract/crafting/recipe_book_data.gd
"""
from __future__ import annotations
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]  # 仓库根(wildwood/)
sys.path.insert(0, str(ROOT))

from core.abstract.crafting.recipe_book import RecipeBook
from core.abstract.crafting.schemas import Recipe, StationType

OUT_PATH = ROOT / "core" / "abstract" / "crafting" / "recipe_book_data.gd"


def _gd_string(s: str) -> str:
    """Python 字符串 → GDScript 双引号字符串(转义 \\ " 和换行)。"""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def dump_recipe_gd(recipe: Recipe) -> str:
    ingredients_gd = "[\n"
    for ing in recipe.ingredients:
        ingredients_gd += f"\t\t\t{{item_id = {_gd_string(ing.item_id)}, count = {ing.count}}},\n"
    ingredients_gd += "\t\t]"

    return f"""\
\t{{
\t\tid = {_gd_string(recipe.id)},
\t\tname = {_gd_string(recipe.name)},
\t\tcategory = {_gd_string(recipe.category.value)},
\t\tstation = {_gd_string(recipe.station.value)},
\t\tingredients = {ingredients_gd},
\t\tresult_item_id = {_gd_string(recipe.result_item_id)},
\t\tresult_count = {recipe.result_count},
\t}}"""


def main():
    book = RecipeBook.default_book()
    recipes = book.all()
    assert len(recipes) >= 30, f"M2.9 要求 ≥30 配方,实际 {len(recipes)}"

    lines = []
    lines.append('## AUTO-GENERATED by core/abstract/crafting/_dump_recipes.py')
    lines.append('## DO NOT EDIT — 改 Python 端 RecipeBook.default_book() 后重跑 dump 脚本')
    lines.append(f'## 共 {len(recipes)} 个配方(M2.9 要求 ≥30)')
    lines.append('class_name WildwoodRecipeBookData')
    lines.append('extends RefCounted')
    lines.append('')
    lines.append('const RECIPES: Array = [')
    for r in recipes:
        lines.append(dump_recipe_gd(r) + ",")
    lines.append(']')
    lines.append('')
    lines.append('')
    lines.append('## 返回所有配方数组(供 demo 与 UI 使用)')
    lines.append('static func default_book() -> Array:')
    lines.append('\treturn RECIPES.duplicate(true)')
    lines.append('')
    lines.append('')
    lines.append('## 按 id 查配方(找不到返 null)')
    lines.append('static func find_by_id(recipe_id: String) -> Dictionary:')
    lines.append('\tfor r in RECIPES:')
    lines.append('\t\tif r["id"] == recipe_id:')
    lines.append('\t\t\treturn r')
    lines.append('\treturn {}')
    lines.append('')
    lines.append('')
    lines.append('## 按 station 过滤(用于分页 / 分类显示)')
    lines.append('static func by_station(station: String) -> Array:')
    lines.append('\tvar out: Array = []')
    lines.append('\tfor r in RECIPES:')
    lines.append('\t\tif r["station"] == station:')
    lines.append('\t\t\tout.append(r)')
    lines.append('\treturn out')
    lines.append('')
    lines.append('')
    lines.append('## 按 category 过滤')
    lines.append('static func by_category(category: String) -> Array:')
    lines.append('\tvar out: Array = []')
    lines.append('\tfor r in RECIPES:')
    lines.append('\t\tif r["category"] == category:')
    lines.append('\t\t\tout.append(r)')
    lines.append('\treturn out')
    lines.append('')

    OUT_PATH.write_text("\n".join(lines))

    # 摘要
    by_station: dict = {}
    by_category: dict = {}
    for r in recipes:
        by_station[r.station.value] = by_station.get(r.station.value, 0) + 1
        by_category[r.category.value] = by_category.get(r.category.value, 0) + 1
    print(f"[dump_recipes] 写出 {OUT_PATH.relative_to(ROOT)}")
    print(f"[dump_recipes] 共 {len(recipes)} 配方")
    print(f"[dump_recipes] by station: {by_station}")
    print(f"[dump_recipes] by category: {by_category}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
