## AUTO-GENERATED by core/abstract/crafting/_dump_recipes.py
## DO NOT EDIT — 改 Python 端 RecipeBook.default_book() 后重跑 dump 脚本
## 共 34 个配方(M2.9 要求 ≥30)
class_name WildwoodRecipeBookData
extends RefCounted

const RECIPES: Array = [
	{
		id = "craft.building.campfire",
		name = "营火",
		category = "building",
		station = "none",
		ingredients = [
			{item_id = "wood", count = 3},
			{item_id = "grass", count = 2},
		],
		result_item_id = "campfire",
		result_count = 1,
	},
	{
		id = "craft.building.chest",
		name = "箱子",
		category = "building",
		station = "workbench",
		ingredients = [
			{item_id = "wood", count = 4},
		],
		result_item_id = "chest",
		result_count = 1,
	},
	{
		id = "craft.building.cookpot",
		name = "烹饪锅",
		category = "building",
		station = "none",
		ingredients = [
			{item_id = "stone", count = 3},
			{item_id = "wood", count = 2},
			{item_id = "rope", count = 1},
		],
		result_item_id = "cookpot",
		result_count = 1,
	},
	{
		id = "craft.building.fire_pit",
		name = "火坑",
		category = "building",
		station = "none",
		ingredients = [
			{item_id = "stone", count = 6},
			{item_id = "wood", count = 4},
		],
		result_item_id = "fire_pit",
		result_count = 1,
	},
	{
		id = "craft.building.tent",
		name = "帐篷",
		category = "building",
		station = "workbench",
		ingredients = [
			{item_id = "wood", count = 6},
			{item_id = "rope", count = 4},
		],
		result_item_id = "tent",
		result_count = 1,
	},
	{
		id = "craft.building.torch_stand",
		name = "火把架",
		category = "building",
		station = "none",
		ingredients = [
			{item_id = "wood", count = 2},
			{item_id = "grass", count = 1},
		],
		result_item_id = "torch_stand",
		result_count = 1,
	},
	{
		id = "craft.building.workbench",
		name = "工作台",
		category = "building",
		station = "none",
		ingredients = [
			{item_id = "wood", count = 4},
			{item_id = "flint", count = 2},
		],
		result_item_id = "workbench",
		result_count = 1,
	},
	{
		id = "craft.equipment.backpack",
		name = "背包",
		category = "equipment",
		station = "workbench",
		ingredients = [
			{item_id = "rope", count = 4},
			{item_id = "grass", count = 4},
		],
		result_item_id = "backpack",
		result_count = 1,
	},
	{
		id = "craft.equipment.boots",
		name = "靴子",
		category = "equipment",
		station = "workbench",
		ingredients = [
			{item_id = "leather", count = 4},
			{item_id = "rope", count = 2},
		],
		result_item_id = "boots",
		result_count = 1,
	},
	{
		id = "craft.equipment.gloves",
		name = "手套",
		category = "equipment",
		station = "workbench",
		ingredients = [
			{item_id = "leather", count = 3},
			{item_id = "rope", count = 1},
		],
		result_item_id = "gloves",
		result_count = 1,
	},
	{
		id = "craft.equipment.helmet_log",
		name = "木盔",
		category = "equipment",
		station = "workbench",
		ingredients = [
			{item_id = "wood", count = 4},
			{item_id = "rope", count = 2},
		],
		result_item_id = "helmet_log",
		result_count = 1,
	},
	{
		id = "craft.equipment.stone_armor",
		name = "石甲",
		category = "equipment",
		station = "workbench",
		ingredients = [
			{item_id = "stone", count = 6},
			{item_id = "rope", count = 4},
		],
		result_item_id = "stone_armor",
		result_count = 1,
	},
	{
		id = "craft.equipment.warm_coat",
		name = "暖外套",
		category = "equipment",
		station = "workbench",
		ingredients = [
			{item_id = "fur", count = 6},
			{item_id = "rope", count = 4},
		],
		result_item_id = "warm_coat",
		result_count = 1,
	},
	{
		id = "craft.equipment.wooden_armor",
		name = "木甲",
		category = "equipment",
		station = "workbench",
		ingredients = [
			{item_id = "wood", count = 8},
			{item_id = "rope", count = 4},
		],
		result_item_id = "wooden_armor",
		result_count = 1,
	},
	{
		id = "craft.food.cooked_berries",
		name = "烤浆果",
		category = "food",
		station = "cookpot",
		ingredients = [
			{item_id = "berries", count = 3},
			{item_id = "wood", count = 1},
		],
		result_item_id = "cooked_berries",
		result_count = 1,
	},
	{
		id = "craft.food.cooked_mushroom",
		name = "烤蘑菇",
		category = "food",
		station = "cookpot",
		ingredients = [
			{item_id = "mushroom", count = 2},
			{item_id = "wood", count = 1},
		],
		result_item_id = "cooked_mushroom",
		result_count = 1,
	},
	{
		id = "craft.food.dried_meat",
		name = "肉干",
		category = "food",
		station = "cookpot",
		ingredients = [
			{item_id = "meat", count = 1},
			{item_id = "wood", count = 1},
		],
		result_item_id = "dried_meat",
		result_count = 1,
	},
	{
		id = "craft.food.fish_stew",
		name = "鱼汤",
		category = "food",
		station = "cookpot",
		ingredients = [
			{item_id = "fish", count = 1},
			{item_id = "mushroom", count = 1},
		],
		result_item_id = "fish_stew",
		result_count = 1,
	},
	{
		id = "craft.food.honey_pie",
		name = "蜜饼",
		category = "food",
		station = "cookpot",
		ingredients = [
			{item_id = "honey", count = 2},
			{item_id = "wood", count = 1},
		],
		result_item_id = "honey_pie",
		result_count = 1,
	},
	{
		id = "craft.food.ice_cream",
		name = "冰淇淋",
		category = "food",
		station = "cookpot",
		ingredients = [
			{item_id = "ice", count = 1},
			{item_id = "honey", count = 1},
		],
		result_item_id = "ice_cream",
		result_count = 1,
	},
	{
		id = "craft.food.meatballs",
		name = "肉丸",
		category = "food",
		station = "cookpot",
		ingredients = [
			{item_id = "meat", count = 1},
			{item_id = "berries", count = 3},
		],
		result_item_id = "meatballs",
		result_count = 1,
	},
	{
		id = "craft.food.steak",
		name = "烤肉",
		category = "food",
		station = "cookpot",
		ingredients = [
			{item_id = "meat", count = 1},
			{item_id = "wood", count = 1},
		],
		result_item_id = "steak",
		result_count = 1,
	},
	{
		id = "craft.food.stuffed_mushroom",
		name = "酿蘑菇",
		category = "food",
		station = "cookpot",
		ingredients = [
			{item_id = "mushroom", count = 2},
			{item_id = "meat", count = 1},
		],
		result_item_id = "stuffed_mushroom",
		result_count = 1,
	},
	{
		id = "craft.food.tea",
		name = "茶",
		category = "food",
		station = "cookpot",
		ingredients = [
			{item_id = "grass", count = 1},
			{item_id = "wood", count = 1},
		],
		result_item_id = "tea",
		result_count = 1,
	},
	{
		id = "craft.food.veggie_soup",
		name = "菜汤",
		category = "food",
		station = "cookpot",
		ingredients = [
			{item_id = "berries", count = 2},
			{item_id = "mushroom", count = 1},
		],
		result_item_id = "veggie_soup",
		result_count = 1,
	},
	{
		id = "craft.tool.axe",
		name = "斧头",
		category = "tool",
		station = "workbench",
		ingredients = [
			{item_id = "wood", count = 3},
		],
		result_item_id = "axe",
		result_count = 1,
	},
	{
		id = "craft.tool.hammer",
		name = "锤子",
		category = "tool",
		station = "workbench",
		ingredients = [
			{item_id = "wood", count = 3},
			{item_id = "stone", count = 2},
		],
		result_item_id = "hammer",
		result_count = 1,
	},
	{
		id = "craft.tool.hoe",
		name = "锄头",
		category = "tool",
		station = "workbench",
		ingredients = [
			{item_id = "wood", count = 2},
			{item_id = "flint", count = 2},
		],
		result_item_id = "hoe",
		result_count = 1,
	},
	{
		id = "craft.tool.knife",
		name = "小刀",
		category = "tool",
		station = "workbench",
		ingredients = [
			{item_id = "wood", count = 1},
			{item_id = "flint", count = 1},
		],
		result_item_id = "knife",
		result_count = 1,
	},
	{
		id = "craft.tool.pickaxe",
		name = "镐",
		category = "tool",
		station = "workbench",
		ingredients = [
			{item_id = "wood", count = 3},
			{item_id = "flint", count = 2},
		],
		result_item_id = "pickaxe",
		result_count = 1,
	},
	{
		id = "craft.tool.rope",
		name = "绳子",
		category = "tool",
		station = "none",
		ingredients = [
			{item_id = "grass", count = 3},
		],
		result_item_id = "rope",
		result_count = 1,
	},
	{
		id = "craft.tool.shovel",
		name = "铲子",
		category = "tool",
		station = "workbench",
		ingredients = [
			{item_id = "wood", count = 2},
			{item_id = "flint", count = 2},
		],
		result_item_id = "shovel",
		result_count = 1,
	},
	{
		id = "craft.tool.spear",
		name = "长矛",
		category = "tool",
		station = "none",
		ingredients = [
			{item_id = "wood", count = 2},
			{item_id = "flint", count = 2},
		],
		result_item_id = "spear",
		result_count = 1,
	},
	{
		id = "craft.tool.torch",
		name = "火把",
		category = "tool",
		station = "none",
		ingredients = [
			{item_id = "wood", count = 1},
			{item_id = "grass", count = 1},
		],
		result_item_id = "torch",
		result_count = 1,
	},
]


## 返回所有配方数组(供 demo 与 UI 使用)
static func default_book() -> Array:
	return RECIPES.duplicate(true)


## 按 id 查配方(找不到返 null)
static func find_by_id(recipe_id: String) -> Dictionary:
	for r in RECIPES:
		if r["id"] == recipe_id:
			return r
	return {}


## 按 station 过滤(用于分页 / 分类显示)
static func by_station(station: String) -> Array:
	var out: Array = []
	for r in RECIPES:
		if r["station"] == station:
			out.append(r)
	return out


## 按 category 过滤
static func by_category(category: String) -> Array:
	var out: Array = []
	for r in RECIPES:
		if r["category"] == category:
			out.append(r)
	return out
