// =====================================================================
// Wildwood 网络协议语义层 — 客户端→服务端 消息 (M1.5)
//
// 设计:
//   - 房间生命周期:Handshake → RoomCreate/Join → (心跳+PlayerInput+ChatMsg)* → RoomLeave
//   - 输入带 input_seq 用于客户端预测(M3.1 校正)
//   - 所有时间戳:uint64 毫秒
// =====================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: wildwood/v1/c2s.proto

package wildwoodv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 客户端首条消息(M1.10 接入时校验版本)
type C2S_Handshake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientVersion string `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"` // 客户端语义版本,例如 "0.1.0"
	PlayerName    string `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`          // ≤ 24 字符(M1.x 不强制唯一)
	AuthToken     string `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`             // 预留:M2.x 接入账号系统
}

func (x *C2S_Handshake) Reset() {
	*x = C2S_Handshake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_c2s_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Handshake) ProtoMessage() {}

func (x *C2S_Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_c2s_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Handshake.ProtoReflect.Descriptor instead.
func (*C2S_Handshake) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_c2s_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_Handshake) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *C2S_Handshake) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *C2S_Handshake) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// 双向心跳(30s 一次,M1.9 房间服务监测连通)
type C2S_Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientTimeMs uint64 `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"` // 客户端发送时刻
	PingSeq      uint32 `protobuf:"varint,2,opt,name=ping_seq,json=pingSeq,proto3" json:"ping_seq,omitempty"`                  // 自增序列,用于 RTT 计算
}

func (x *C2S_Heartbeat) Reset() {
	*x = C2S_Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_c2s_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Heartbeat) ProtoMessage() {}

func (x *C2S_Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_c2s_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Heartbeat.ProtoReflect.Descriptor instead.
func (*C2S_Heartbeat) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_c2s_proto_rawDescGZIP(), []int{1}
}

func (x *C2S_Heartbeat) GetClientTimeMs() uint64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

func (x *C2S_Heartbeat) GetPingSeq() uint32 {
	if x != nil {
		return x.PingSeq
	}
	return 0
}

// 主动断开(优雅退出,服务器立即释放槽位)
type C2S_Disconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // "user_quit" / "client_crash" / ...
}

func (x *C2S_Disconnect) Reset() {
	*x = C2S_Disconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_c2s_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Disconnect) ProtoMessage() {}

func (x *C2S_Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_c2s_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Disconnect.ProtoReflect.Descriptor instead.
func (*C2S_Disconnect) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_c2s_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_Disconnect) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type C2S_RoomCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomName   string `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`        // ≤ 32 字符
	WorldSeed  string `protobuf:"bytes,2,opt,name=world_seed,json=worldSeed,proto3" json:"world_seed,omitempty"`     // 32-bit seed 字符串形式
	MaxPlayers uint32 `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"` // 服务端硬上限 4,客户端 < 4 即可
}

func (x *C2S_RoomCreate) Reset() {
	*x = C2S_RoomCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_c2s_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_RoomCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RoomCreate) ProtoMessage() {}

func (x *C2S_RoomCreate) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_c2s_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RoomCreate.ProtoReflect.Descriptor instead.
func (*C2S_RoomCreate) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_c2s_proto_rawDescGZIP(), []int{3}
}

func (x *C2S_RoomCreate) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *C2S_RoomCreate) GetWorldSeed() string {
	if x != nil {
		return x.WorldSeed
	}
	return ""
}

func (x *C2S_RoomCreate) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type C2S_RoomJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`          // 服务端分配(5 位短链)
	JoinToken string `protobuf:"bytes,2,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"` // 创建时由服务端下发,加入校验
}

func (x *C2S_RoomJoin) Reset() {
	*x = C2S_RoomJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_c2s_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_RoomJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RoomJoin) ProtoMessage() {}

func (x *C2S_RoomJoin) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_c2s_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RoomJoin.ProtoReflect.Descriptor instead.
func (*C2S_RoomJoin) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_c2s_proto_rawDescGZIP(), []int{4}
}

func (x *C2S_RoomJoin) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *C2S_RoomJoin) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

type C2S_RoomLeave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *C2S_RoomLeave) Reset() {
	*x = C2S_RoomLeave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_c2s_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_RoomLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RoomLeave) ProtoMessage() {}

func (x *C2S_RoomLeave) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_c2s_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RoomLeave.ProtoReflect.Descriptor instead.
func (*C2S_RoomLeave) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_c2s_proto_rawDescGZIP(), []int{5}
}

func (x *C2S_RoomLeave) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// 房主踢人(M1.11 验收 ②)
//   - 仅 host 可调用,非 host 返回 ROOM_ERROR_INVALID_INPUT
//   - 服务端校验:目标在同房间 + 调用者是 host
//   - 成功后:被踢者收到 S2C_RoomKicked(reason="kicked_by_host"),
//     全队收到 S2C_PlayerLeft(reason="kicked"),槽位立即释放
type C2S_RoomKick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId         string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TargetPlayerId string `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"` // 要踢出的玩家 id
	Reason         string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                         // 房主留言(≤ 64 字符),被踢客户端可显示
}

func (x *C2S_RoomKick) Reset() {
	*x = C2S_RoomKick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_c2s_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_RoomKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RoomKick) ProtoMessage() {}

func (x *C2S_RoomKick) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_c2s_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RoomKick.ProtoReflect.Descriptor instead.
func (*C2S_RoomKick) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_c2s_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_RoomKick) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *C2S_RoomKick) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *C2S_RoomKick) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 房间列表查询(大厅 UI,M2.x 接入)
type C2S_RoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 0-based
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // ≤ 32
}

func (x *C2S_RoomList) Reset() {
	*x = C2S_RoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_c2s_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_RoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RoomList) ProtoMessage() {}

func (x *C2S_RoomList) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_c2s_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RoomList.ProtoReflect.Descriptor instead.
func (*C2S_RoomList) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_c2s_proto_rawDescGZIP(), []int{7}
}

func (x *C2S_RoomList) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *C2S_RoomList) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 一次输入可以是移动/攻击/采集/建造/使用/复活/互动
// 服务端 20Hz tick 校验(M1.9 节奏),用 input_seq 关联预测(M3.1)
type C2S_PlayerInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputSeq   uint32      `protobuf:"varint,1,opt,name=input_seq,json=inputSeq,proto3" json:"input_seq,omitempty"`       // 客户端自增,房间内唯一
	ServerTick uint32      `protobuf:"varint,2,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"` // 客户端参考的服务端 tick(可晚于真实)
	Action     InputAction `protobuf:"varint,3,opt,name=action,proto3,enum=wildwood.net.v1.InputAction" json:"action,omitempty"`
	// === 按 action 取以下字段 ===
	MoveDx         float32 `protobuf:"fixed32,4,opt,name=move_dx,json=moveDx,proto3" json:"move_dx,omitempty"`                          // MOVE:  [-1, 1]
	MoveDy         float32 `protobuf:"fixed32,5,opt,name=move_dy,json=moveDy,proto3" json:"move_dy,omitempty"`                          // MOVE:  [-1, 1]
	TargetEntityId uint32  `protobuf:"varint,6,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"` // ATTACK/GATHER/USE_ITEM/INTERACT
	TargetPrefabId uint32  `protobuf:"varint,7,opt,name=target_prefab_id,json=targetPrefabId,proto3" json:"target_prefab_id,omitempty"` // BUILD: prefab id
	TileX          int32   `protobuf:"zigzag32,8,opt,name=tile_x,json=tileX,proto3" json:"tile_x,omitempty"`                            // BUILD: 网格坐标
	TileY          int32   `protobuf:"zigzag32,9,opt,name=tile_y,json=tileY,proto3" json:"tile_y,omitempty"`                            // BUILD: 网格坐标
	SlotIndex      uint32  `protobuf:"varint,10,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`                 // USE_ITEM: 快捷栏 0-9
	Facing         float32 `protobuf:"fixed32,11,opt,name=facing,proto3" json:"facing,omitempty"`                                       // 朝向 0-2π
	ClientTimeMs   uint64  `protobuf:"varint,12,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`      // 客户端时间戳
}

func (x *C2S_PlayerInput) Reset() {
	*x = C2S_PlayerInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_c2s_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_PlayerInput) ProtoMessage() {}

func (x *C2S_PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_c2s_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_PlayerInput.ProtoReflect.Descriptor instead.
func (*C2S_PlayerInput) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_c2s_proto_rawDescGZIP(), []int{8}
}

func (x *C2S_PlayerInput) GetInputSeq() uint32 {
	if x != nil {
		return x.InputSeq
	}
	return 0
}

func (x *C2S_PlayerInput) GetServerTick() uint32 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *C2S_PlayerInput) GetAction() InputAction {
	if x != nil {
		return x.Action
	}
	return InputAction_INPUT_ACTION_UNSPECIFIED
}

func (x *C2S_PlayerInput) GetMoveDx() float32 {
	if x != nil {
		return x.MoveDx
	}
	return 0
}

func (x *C2S_PlayerInput) GetMoveDy() float32 {
	if x != nil {
		return x.MoveDy
	}
	return 0
}

func (x *C2S_PlayerInput) GetTargetEntityId() uint32 {
	if x != nil {
		return x.TargetEntityId
	}
	return 0
}

func (x *C2S_PlayerInput) GetTargetPrefabId() uint32 {
	if x != nil {
		return x.TargetPrefabId
	}
	return 0
}

func (x *C2S_PlayerInput) GetTileX() int32 {
	if x != nil {
		return x.TileX
	}
	return 0
}

func (x *C2S_PlayerInput) GetTileY() int32 {
	if x != nil {
		return x.TileY
	}
	return 0
}

func (x *C2S_PlayerInput) GetSlotIndex() uint32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *C2S_PlayerInput) GetFacing() float32 {
	if x != nil {
		return x.Facing
	}
	return 0
}

func (x *C2S_PlayerInput) GetClientTimeMs() uint64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

type C2S_ChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel        ChatChannel `protobuf:"varint,1,opt,name=channel,proto3,enum=wildwood.net.v1.ChatChannel" json:"channel,omitempty"`
	TargetPlayerId string      `protobuf:"bytes,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"` // PRIVATE 时填写
	Text           string      `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`                                             // ≤ 256 字符
	ClientTimeMs   uint64      `protobuf:"varint,4,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
}

func (x *C2S_ChatMsg) Reset() {
	*x = C2S_ChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_c2s_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_ChatMsg) ProtoMessage() {}

func (x *C2S_ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_c2s_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_ChatMsg.ProtoReflect.Descriptor instead.
func (*C2S_ChatMsg) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_c2s_proto_rawDescGZIP(), []int{9}
}

func (x *C2S_ChatMsg) GetChannel() ChatChannel {
	if x != nil {
		return x.Channel
	}
	return ChatChannel_CHAT_CHANNEL_UNSPECIFIED
}

func (x *C2S_ChatMsg) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *C2S_ChatMsg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *C2S_ChatMsg) GetClientTimeMs() uint64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

var File_wildwood_v1_c2s_proto protoreflect.FileDescriptor

var file_wildwood_v1_c2s_proto_rawDesc = []byte{
	0x0a, 0x15, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x32,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f,
	0x64, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x18, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f,
	0x6f, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x76, 0x0a, 0x0d, 0x43, 0x32, 0x53, 0x5f, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68,
	0x61, 0x6b, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x75, 0x74, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x50, 0x0a, 0x0d, 0x43, 0x32,
	0x53, 0x5f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x4d,
	0x73, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x71, 0x22, 0x28, 0x0a, 0x0e,
	0x43, 0x32, 0x53, 0x5f, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x6d, 0x0a, 0x0e, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x6f,
	0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f,
	0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x5f, 0x73,
	0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x53, 0x65, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x46, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x6f, 0x6f,
	0x6d, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x28, 0x0a,
	0x0d, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x69, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x5f, 0x52,
	0x6f, 0x6f, 0x6d, 0x4b, 0x69, 0x63, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x28, 0x0a, 0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x22, 0x3f, 0x0a, 0x0c, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x96, 0x03, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x5f, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x53, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74,
	0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x34, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64,
	0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x6d,
	0x6f, 0x76, 0x65, 0x5f, 0x64, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x6d, 0x6f,
	0x76, 0x65, 0x44, 0x78, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x64, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x79, 0x12, 0x28, 0x0a,
	0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x61, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x72, 0x65, 0x66, 0x61, 0x62, 0x49,
	0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x69, 0x6c, 0x65, 0x5f, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x11, 0x52, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x58, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x69, 0x6c, 0x65,
	0x5f, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x59, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16,
	0x0a, 0x06, 0x66, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x66, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x22, 0xa9, 0x01, 0x0a,
	0x0b, 0x43, 0x32, 0x53, 0x5f, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x36, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2f,
	0x6e, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x77, 0x69, 0x6c,
	0x64, 0x77, 0x6f, 0x6f, 0x64, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wildwood_v1_c2s_proto_rawDescOnce sync.Once
	file_wildwood_v1_c2s_proto_rawDescData = file_wildwood_v1_c2s_proto_rawDesc
)

func file_wildwood_v1_c2s_proto_rawDescGZIP() []byte {
	file_wildwood_v1_c2s_proto_rawDescOnce.Do(func() {
		file_wildwood_v1_c2s_proto_rawDescData = protoimpl.X.CompressGZIP(file_wildwood_v1_c2s_proto_rawDescData)
	})
	return file_wildwood_v1_c2s_proto_rawDescData
}

var file_wildwood_v1_c2s_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_wildwood_v1_c2s_proto_goTypes = []any{
	(*C2S_Handshake)(nil),   // 0: wildwood.net.v1.C2S_Handshake
	(*C2S_Heartbeat)(nil),   // 1: wildwood.net.v1.C2S_Heartbeat
	(*C2S_Disconnect)(nil),  // 2: wildwood.net.v1.C2S_Disconnect
	(*C2S_RoomCreate)(nil),  // 3: wildwood.net.v1.C2S_RoomCreate
	(*C2S_RoomJoin)(nil),    // 4: wildwood.net.v1.C2S_RoomJoin
	(*C2S_RoomLeave)(nil),   // 5: wildwood.net.v1.C2S_RoomLeave
	(*C2S_RoomKick)(nil),    // 6: wildwood.net.v1.C2S_RoomKick
	(*C2S_RoomList)(nil),    // 7: wildwood.net.v1.C2S_RoomList
	(*C2S_PlayerInput)(nil), // 8: wildwood.net.v1.C2S_PlayerInput
	(*C2S_ChatMsg)(nil),     // 9: wildwood.net.v1.C2S_ChatMsg
	(InputAction)(0),        // 10: wildwood.net.v1.InputAction
	(ChatChannel)(0),        // 11: wildwood.net.v1.ChatChannel
}
var file_wildwood_v1_c2s_proto_depIdxs = []int32{
	10, // 0: wildwood.net.v1.C2S_PlayerInput.action:type_name -> wildwood.net.v1.InputAction
	11, // 1: wildwood.net.v1.C2S_ChatMsg.channel:type_name -> wildwood.net.v1.ChatChannel
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_wildwood_v1_c2s_proto_init() }
func file_wildwood_v1_c2s_proto_init() {
	if File_wildwood_v1_c2s_proto != nil {
		return
	}
	file_wildwood_v1_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_wildwood_v1_c2s_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*C2S_Handshake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_c2s_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*C2S_Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_c2s_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*C2S_Disconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_c2s_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*C2S_RoomCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_c2s_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*C2S_RoomJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_c2s_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*C2S_RoomLeave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_c2s_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*C2S_RoomKick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_c2s_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*C2S_RoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_c2s_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*C2S_PlayerInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_c2s_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*C2S_ChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wildwood_v1_c2s_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wildwood_v1_c2s_proto_goTypes,
		DependencyIndexes: file_wildwood_v1_c2s_proto_depIdxs,
		MessageInfos:      file_wildwood_v1_c2s_proto_msgTypes,
	}.Build()
	File_wildwood_v1_c2s_proto = out.File
	file_wildwood_v1_c2s_proto_rawDesc = nil
	file_wildwood_v1_c2s_proto_goTypes = nil
	file_wildwood_v1_c2s_proto_depIdxs = nil
}
