// =====================================================================
// Wildwood 网络协议语义层 — 服务端→客户端 消息 (M1.5)
//
// 设计:
//   - WorldDelta 是核心节流消息:20Hz tick,含权威状态变化 + 客户端输入 ack
//   - 房间生命周期事件以独立消息广播,便于路由
//   - 错误/广播/聊天用最高优先级通道(不可丢弃)
// =====================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: wildwood/v1/s2c.proto

package wildwoodv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 握手确认(M1.10 接入后下发,携带会话凭证)
type S2C_HandshakeAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerVersion  string `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	PlayerId       string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`                      // 服务端 UUID
	SessionToken   string `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`          // 用于后续消息鉴权
	ServerTickRate uint32 `protobuf:"varint,4,opt,name=server_tick_rate,json=serverTickRate,proto3" json:"server_tick_rate,omitempty"` // 20 (Hz)
	MaxRoomPlayers uint32 `protobuf:"varint,5,opt,name=max_room_players,json=maxRoomPlayers,proto3" json:"max_room_players,omitempty"` // 4
}

func (x *S2C_HandshakeAck) Reset() {
	*x = S2C_HandshakeAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_HandshakeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_HandshakeAck) ProtoMessage() {}

func (x *S2C_HandshakeAck) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_HandshakeAck.ProtoReflect.Descriptor instead.
func (*S2C_HandshakeAck) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{0}
}

func (x *S2C_HandshakeAck) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *S2C_HandshakeAck) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *S2C_HandshakeAck) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *S2C_HandshakeAck) GetServerTickRate() uint32 {
	if x != nil {
		return x.ServerTickRate
	}
	return 0
}

func (x *S2C_HandshakeAck) GetMaxRoomPlayers() uint32 {
	if x != nil {
		return x.MaxRoomPlayers
	}
	return 0
}

// 心跳回包(回显 + 服务端时间)
type S2C_HeartbeatAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientTimeMs uint64 `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"` // 回显
	PingSeq      uint32 `protobuf:"varint,2,opt,name=ping_seq,json=pingSeq,proto3" json:"ping_seq,omitempty"`
	ServerTimeMs uint64 `protobuf:"varint,3,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
}

func (x *S2C_HeartbeatAck) Reset() {
	*x = S2C_HeartbeatAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_HeartbeatAck) ProtoMessage() {}

func (x *S2C_HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_HeartbeatAck.ProtoReflect.Descriptor instead.
func (*S2C_HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_HeartbeatAck) GetClientTimeMs() uint64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

func (x *S2C_HeartbeatAck) GetPingSeq() uint32 {
	if x != nil {
		return x.PingSeq
	}
	return 0
}

func (x *S2C_HeartbeatAck) GetServerTimeMs() uint64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

type S2C_RoomCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	JoinToken  string `protobuf:"bytes,2,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	MaxPlayers uint32 `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
}

func (x *S2C_RoomCreated) Reset() {
	*x = S2C_RoomCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RoomCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RoomCreated) ProtoMessage() {}

func (x *S2C_RoomCreated) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RoomCreated.ProtoReflect.Descriptor instead.
func (*S2C_RoomCreated) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{2}
}

func (x *S2C_RoomCreated) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *S2C_RoomCreated) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *S2C_RoomCreated) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

// 加入成功:带初始快照,客户端用其构建世界
type S2C_RoomJoined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId       string         `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId     string         `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Members      []*PlayerState `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	InitialState *WorldSnapshot `protobuf:"bytes,4,opt,name=initial_state,json=initialState,proto3" json:"initial_state,omitempty"`
	ServerTick   uint32         `protobuf:"varint,5,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
}

func (x *S2C_RoomJoined) Reset() {
	*x = S2C_RoomJoined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RoomJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RoomJoined) ProtoMessage() {}

func (x *S2C_RoomJoined) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RoomJoined.ProtoReflect.Descriptor instead.
func (*S2C_RoomJoined) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_RoomJoined) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *S2C_RoomJoined) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *S2C_RoomJoined) GetMembers() []*PlayerState {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *S2C_RoomJoined) GetInitialState() *WorldSnapshot {
	if x != nil {
		return x.InitialState
	}
	return nil
}

func (x *S2C_RoomJoined) GetServerTick() uint32 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

type S2C_RoomLeft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *S2C_RoomLeft) Reset() {
	*x = S2C_RoomLeft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RoomLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RoomLeft) ProtoMessage() {}

func (x *S2C_RoomLeft) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RoomLeft.ProtoReflect.Descriptor instead.
func (*S2C_RoomLeft) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_RoomLeft) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *S2C_RoomLeft) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 队伍槽变化(广播)
type S2C_PlayerJoined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string       `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Player *PlayerState `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *S2C_PlayerJoined) Reset() {
	*x = S2C_PlayerJoined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_PlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_PlayerJoined) ProtoMessage() {}

func (x *S2C_PlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_PlayerJoined.ProtoReflect.Descriptor instead.
func (*S2C_PlayerJoined) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{5}
}

func (x *S2C_PlayerJoined) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *S2C_PlayerJoined) GetPlayer() *PlayerState {
	if x != nil {
		return x.Player
	}
	return nil
}

type S2C_PlayerLeft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Reason   string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // "leave" / "kicked" / "timeout" / "crash"
}

func (x *S2C_PlayerLeft) Reset() {
	*x = S2C_PlayerLeft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_PlayerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_PlayerLeft) ProtoMessage() {}

func (x *S2C_PlayerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_PlayerLeft.ProtoReflect.Descriptor instead.
func (*S2C_PlayerLeft) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{6}
}

func (x *S2C_PlayerLeft) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *S2C_PlayerLeft) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *S2C_PlayerLeft) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 被踢通知(给被踢客户端;其他人只看到 PlayerLeft)
type S2C_RoomKicked struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId       string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	KickedById   string `protobuf:"bytes,2,opt,name=kicked_by_id,json=kickedById,proto3" json:"kicked_by_id,omitempty"` // 谁踢的(房主 id)
	Reason       string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                             // 房主留言或 "kicked_by_host"
	ServerTimeMs uint64 `protobuf:"varint,4,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
}

func (x *S2C_RoomKicked) Reset() {
	*x = S2C_RoomKicked{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RoomKicked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RoomKicked) ProtoMessage() {}

func (x *S2C_RoomKicked) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RoomKicked.ProtoReflect.Descriptor instead.
func (*S2C_RoomKicked) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{7}
}

func (x *S2C_RoomKicked) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *S2C_RoomKicked) GetKickedById() string {
	if x != nil {
		return x.KickedById
	}
	return ""
}

func (x *S2C_RoomKicked) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *S2C_RoomKicked) GetServerTimeMs() uint64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

// 房间状态变化(成员数变化时由服务端主动广播,玩家 UI 刷新槽位)
type S2C_RoomStateChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId         string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CurrentPlayers uint32 `protobuf:"varint,2,opt,name=current_players,json=currentPlayers,proto3" json:"current_players,omitempty"`
	MaxPlayers     uint32 `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Trigger        string `protobuf:"bytes,4,opt,name=trigger,proto3" json:"trigger,omitempty"` // "join" / "leave" / "kick" / "disconnect"
}

func (x *S2C_RoomStateChanged) Reset() {
	*x = S2C_RoomStateChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RoomStateChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RoomStateChanged) ProtoMessage() {}

func (x *S2C_RoomStateChanged) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RoomStateChanged.ProtoReflect.Descriptor instead.
func (*S2C_RoomStateChanged) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{8}
}

func (x *S2C_RoomStateChanged) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *S2C_RoomStateChanged) GetCurrentPlayers() uint32 {
	if x != nil {
		return x.CurrentPlayers
	}
	return 0
}

func (x *S2C_RoomStateChanged) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *S2C_RoomStateChanged) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

type S2C_RoomState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId         string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CurrentPlayers uint32 `protobuf:"varint,2,opt,name=current_players,json=currentPlayers,proto3" json:"current_players,omitempty"`
	MaxPlayers     uint32 `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	IsOpen         bool   `protobuf:"varint,4,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
}

func (x *S2C_RoomState) Reset() {
	*x = S2C_RoomState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RoomState) ProtoMessage() {}

func (x *S2C_RoomState) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RoomState.ProtoReflect.Descriptor instead.
func (*S2C_RoomState) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{9}
}

func (x *S2C_RoomState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *S2C_RoomState) GetCurrentPlayers() uint32 {
	if x != nil {
		return x.CurrentPlayers
	}
	return 0
}

func (x *S2C_RoomState) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *S2C_RoomState) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

type S2C_RoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*S2C_RoomState `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Total uint32           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总房间数(分页用)
}

func (x *S2C_RoomList) Reset() {
	*x = S2C_RoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RoomList) ProtoMessage() {}

func (x *S2C_RoomList) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RoomList.ProtoReflect.Descriptor instead.
func (*S2C_RoomList) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{10}
}

func (x *S2C_RoomList) GetRooms() []*S2C_RoomState {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *S2C_RoomList) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 20Hz tick 一次;包含 acked_input_seqs 用于客户端预测校正
// 字节预算:< 4 KB/tick(4 人小队 + 200 实体/视野)
type S2C_WorldDelta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTick   uint32 `protobuf:"varint,1,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	ServerTimeMs uint64 `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	// 已被服务端确认的客户端输入 seq(M3.1 预测校正用)
	AckedInputSeqs []uint32 `protobuf:"varint,3,rep,packed,name=acked_input_seqs,json=ackedInputSeqs,proto3" json:"acked_input_seqs,omitempty"`
	// 权威状态变化(增量;不在此包内的实体 = 无变化)
	EntityUpdates    []*EntityState `protobuf:"bytes,4,rep,name=entity_updates,json=entityUpdates,proto3" json:"entity_updates,omitempty"`
	RemovedEntityIds []uint32       `protobuf:"varint,5,rep,packed,name=removed_entity_ids,json=removedEntityIds,proto3" json:"removed_entity_ids,omitempty"`
	// 队伍槽位状态(只给条形 %)
	PlayerStatus []*PlayerStatus `protobuf:"bytes,6,rep,name=player_status,json=playerStatus,proto3" json:"player_status,omitempty"`
	// 资源/建造/攻击/死亡事件
	Events []*WorldEvent `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *S2C_WorldDelta) Reset() {
	*x = S2C_WorldDelta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_WorldDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_WorldDelta) ProtoMessage() {}

func (x *S2C_WorldDelta) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_WorldDelta.ProtoReflect.Descriptor instead.
func (*S2C_WorldDelta) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{11}
}

func (x *S2C_WorldDelta) GetServerTick() uint32 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2C_WorldDelta) GetServerTimeMs() uint64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *S2C_WorldDelta) GetAckedInputSeqs() []uint32 {
	if x != nil {
		return x.AckedInputSeqs
	}
	return nil
}

func (x *S2C_WorldDelta) GetEntityUpdates() []*EntityState {
	if x != nil {
		return x.EntityUpdates
	}
	return nil
}

func (x *S2C_WorldDelta) GetRemovedEntityIds() []uint32 {
	if x != nil {
		return x.RemovedEntityIds
	}
	return nil
}

func (x *S2C_WorldDelta) GetPlayerStatus() []*PlayerStatus {
	if x != nil {
		return x.PlayerStatus
	}
	return nil
}

func (x *S2C_WorldDelta) GetEvents() []*WorldEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type S2C_ChatBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel        ChatChannel `protobuf:"varint,1,opt,name=channel,proto3,enum=wildwood.net.v1.ChatChannel" json:"channel,omitempty"`
	SenderId       string      `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName     string      `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	TargetPlayerId string      `protobuf:"bytes,4,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"` // PRIVATE 收件人
	Text           string      `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	ServerTimeMs   uint64      `protobuf:"varint,6,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
}

func (x *S2C_ChatBroadcast) Reset() {
	*x = S2C_ChatBroadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_ChatBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ChatBroadcast) ProtoMessage() {}

func (x *S2C_ChatBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ChatBroadcast.ProtoReflect.Descriptor instead.
func (*S2C_ChatBroadcast) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{12}
}

func (x *S2C_ChatBroadcast) GetChannel() ChatChannel {
	if x != nil {
		return x.Channel
	}
	return ChatChannel_CHAT_CHANNEL_UNSPECIFIED
}

func (x *S2C_ChatBroadcast) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *S2C_ChatBroadcast) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *S2C_ChatBroadcast) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *S2C_ChatBroadcast) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *S2C_ChatBroadcast) GetServerTimeMs() uint64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

type S2C_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    RoomErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=wildwood.net.v1.RoomErrorCode" json:"code,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Context string        `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"` // 关联的 room_id / player_id / ...
}

func (x *S2C_Error) Reset() {
	*x = S2C_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Error) ProtoMessage() {}

func (x *S2C_Error) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Error.ProtoReflect.Descriptor instead.
func (*S2C_Error) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{13}
}

func (x *S2C_Error) GetCode() RoomErrorCode {
	if x != nil {
		return x.Code
	}
	return RoomErrorCode_ROOM_ERROR_UNSPECIFIED
}

func (x *S2C_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *S2C_Error) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

// 房间加入时全量下发 — 图鉴数据库 + 当前解锁字典
// 客户端用 database 渲染所有槽位(已解锁显示完整,未解锁灰显 + ??)
// 用 unlocked 决定每个槽位状态
// 字节预算:31 entries × ~120B + 解锁数 × 30B ≈ 4-8 KB(join 时一次)
type S2C_CodexSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTick   uint32         `protobuf:"varint,1,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	ServerTimeMs uint64         `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	Database     []*CodexEntry  `protobuf:"bytes,3,rep,name=database,proto3" json:"database,omitempty"` // 全量数据库
	Unlocked     []*CodexUnlock `protobuf:"bytes,4,rep,name=unlocked,proto3" json:"unlocked,omitempty"` // 已解锁列表(可空,新房间)
}

func (x *S2C_CodexSync) Reset() {
	*x = S2C_CodexSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_CodexSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_CodexSync) ProtoMessage() {}

func (x *S2C_CodexSync) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_CodexSync.ProtoReflect.Descriptor instead.
func (*S2C_CodexSync) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{14}
}

func (x *S2C_CodexSync) GetServerTick() uint32 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2C_CodexSync) GetServerTimeMs() uint64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *S2C_CodexSync) GetDatabase() []*CodexEntry {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *S2C_CodexSync) GetUnlocked() []*CodexUnlock {
	if x != nil {
		return x.Unlocked
	}
	return nil
}

// 5Hz 增量广播 — 队伍中任一玩家解锁新条目时,服务端周期性广播完整 unlocked 表
// 简化版(M2.11):每次发整张 unlocked 表(典型 4-50 项,字节 < 256B)
// M3.x 接管后会改为 only-delta
type S2C_CodexDelta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTick   uint32         `protobuf:"varint,1,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	ServerTimeMs uint64         `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	UnlockedFull []*CodexUnlock `protobuf:"bytes,3,rep,name=unlocked_full,json=unlockedFull,proto3" json:"unlocked_full,omitempty"` // 完整已解锁表
}

func (x *S2C_CodexDelta) Reset() {
	*x = S2C_CodexDelta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_s2c_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_CodexDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_CodexDelta) ProtoMessage() {}

func (x *S2C_CodexDelta) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_s2c_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_CodexDelta.ProtoReflect.Descriptor instead.
func (*S2C_CodexDelta) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_s2c_proto_rawDescGZIP(), []int{15}
}

func (x *S2C_CodexDelta) GetServerTick() uint32 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *S2C_CodexDelta) GetServerTimeMs() uint64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *S2C_CodexDelta) GetUnlockedFull() []*CodexUnlock {
	if x != nil {
		return x.UnlockedFull
	}
	return nil
}

var File_wildwood_v1_s2c_proto protoreflect.FileDescriptor

var file_wildwood_v1_s2c_proto_rawDesc = []byte{
	0x0a, 0x15, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x32,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f,
	0x64, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x18, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f,
	0x6f, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xcf, 0x01, 0x0a, 0x10, 0x53, 0x32, 0x43, 0x5f, 0x48, 0x61, 0x6e, 0x64, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x41, 0x63, 0x6b, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x28, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x5f,
	0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x52, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x61,
	0x78, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x22, 0x79, 0x0a, 0x10, 0x53, 0x32, 0x43, 0x5f, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x22,
	0x6a, 0x0a, 0x0f, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6a,
	0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61,
	0x78, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x6d, 0x61, 0x78, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0xe4, 0x01, 0x0a, 0x0e,
	0x53, 0x32, 0x43, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64,
	0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x43, 0x0a, 0x0d,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2e, 0x6e,
	0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x52, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x63, 0x6b,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69,
	0x63, 0x6b, 0x22, 0x3f, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x65,
	0x66, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x22, 0x61, 0x0a, 0x10, 0x53, 0x32, 0x43, 0x5f, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x34, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2e, 0x6e, 0x65, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x5e, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x5f, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x89, 0x01, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x5f, 0x52,
	0x6f, 0x6f, 0x6d, 0x4b, 0x69, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6b, 0x69, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6b, 0x69, 0x63, 0x6b, 0x65, 0x64,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x4d, 0x73, 0x22, 0x93, 0x01, 0x0a, 0x14, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x53, 0x32, 0x43,
	0x5f, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x6d, 0x61, 0x78, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x69, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x22, 0x5a, 0x0a, 0x0c, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x6f,
	0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64,
	0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x6f, 0x6f, 0x6d,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x22, 0xed, 0x02, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x5f, 0x57, 0x6f, 0x72, 0x6c, 0x64,
	0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x74, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x12, 0x28, 0x0a, 0x10,
	0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x71, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0e, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x53, 0x65, 0x71, 0x73, 0x12, 0x43, 0x0a, 0x0e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0d, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x10, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x73, 0x12, 0x42, 0x0a, 0x0d, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2e, 0x6e, 0x65, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x33, 0x0a,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0xed, 0x01, 0x0a, 0x11, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x68, 0x61, 0x74, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x77, 0x69, 0x6c, 0x64,
	0x77, 0x6f, 0x6f, 0x64, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28,
	0x0a, 0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x24, 0x0a, 0x0e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x4d, 0x73, 0x22, 0x73, 0x0a, 0x09, 0x53, 0x32, 0x43, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x32, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e,
	0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0xc9, 0x01, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x5f,
	0x43, 0x6f, 0x64, 0x65, 0x78, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73,
	0x12, 0x37, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2e, 0x6e, 0x65,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x78, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x75, 0x6e, 0x6c,
	0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x69,
	0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x64, 0x65, 0x78, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x08, 0x75, 0x6e, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x22, 0x9a, 0x01, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x6f, 0x64, 0x65,
	0x78, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x12, 0x41, 0x0a,
	0x0d, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2e,
	0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x78, 0x55, 0x6e, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x0c, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x46, 0x75, 0x6c, 0x6c,
	0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77,
	0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2f, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wildwood_v1_s2c_proto_rawDescOnce sync.Once
	file_wildwood_v1_s2c_proto_rawDescData = file_wildwood_v1_s2c_proto_rawDesc
)

func file_wildwood_v1_s2c_proto_rawDescGZIP() []byte {
	file_wildwood_v1_s2c_proto_rawDescOnce.Do(func() {
		file_wildwood_v1_s2c_proto_rawDescData = protoimpl.X.CompressGZIP(file_wildwood_v1_s2c_proto_rawDescData)
	})
	return file_wildwood_v1_s2c_proto_rawDescData
}

var file_wildwood_v1_s2c_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_wildwood_v1_s2c_proto_goTypes = []any{
	(*S2C_HandshakeAck)(nil),     // 0: wildwood.net.v1.S2C_HandshakeAck
	(*S2C_HeartbeatAck)(nil),     // 1: wildwood.net.v1.S2C_HeartbeatAck
	(*S2C_RoomCreated)(nil),      // 2: wildwood.net.v1.S2C_RoomCreated
	(*S2C_RoomJoined)(nil),       // 3: wildwood.net.v1.S2C_RoomJoined
	(*S2C_RoomLeft)(nil),         // 4: wildwood.net.v1.S2C_RoomLeft
	(*S2C_PlayerJoined)(nil),     // 5: wildwood.net.v1.S2C_PlayerJoined
	(*S2C_PlayerLeft)(nil),       // 6: wildwood.net.v1.S2C_PlayerLeft
	(*S2C_RoomKicked)(nil),       // 7: wildwood.net.v1.S2C_RoomKicked
	(*S2C_RoomStateChanged)(nil), // 8: wildwood.net.v1.S2C_RoomStateChanged
	(*S2C_RoomState)(nil),        // 9: wildwood.net.v1.S2C_RoomState
	(*S2C_RoomList)(nil),         // 10: wildwood.net.v1.S2C_RoomList
	(*S2C_WorldDelta)(nil),       // 11: wildwood.net.v1.S2C_WorldDelta
	(*S2C_ChatBroadcast)(nil),    // 12: wildwood.net.v1.S2C_ChatBroadcast
	(*S2C_Error)(nil),            // 13: wildwood.net.v1.S2C_Error
	(*S2C_CodexSync)(nil),        // 14: wildwood.net.v1.S2C_CodexSync
	(*S2C_CodexDelta)(nil),       // 15: wildwood.net.v1.S2C_CodexDelta
	(*PlayerState)(nil),          // 16: wildwood.net.v1.PlayerState
	(*WorldSnapshot)(nil),        // 17: wildwood.net.v1.WorldSnapshot
	(*EntityState)(nil),          // 18: wildwood.net.v1.EntityState
	(*PlayerStatus)(nil),         // 19: wildwood.net.v1.PlayerStatus
	(*WorldEvent)(nil),           // 20: wildwood.net.v1.WorldEvent
	(ChatChannel)(0),             // 21: wildwood.net.v1.ChatChannel
	(RoomErrorCode)(0),           // 22: wildwood.net.v1.RoomErrorCode
	(*CodexEntry)(nil),           // 23: wildwood.net.v1.CodexEntry
	(*CodexUnlock)(nil),          // 24: wildwood.net.v1.CodexUnlock
}
var file_wildwood_v1_s2c_proto_depIdxs = []int32{
	16, // 0: wildwood.net.v1.S2C_RoomJoined.members:type_name -> wildwood.net.v1.PlayerState
	17, // 1: wildwood.net.v1.S2C_RoomJoined.initial_state:type_name -> wildwood.net.v1.WorldSnapshot
	16, // 2: wildwood.net.v1.S2C_PlayerJoined.player:type_name -> wildwood.net.v1.PlayerState
	9,  // 3: wildwood.net.v1.S2C_RoomList.rooms:type_name -> wildwood.net.v1.S2C_RoomState
	18, // 4: wildwood.net.v1.S2C_WorldDelta.entity_updates:type_name -> wildwood.net.v1.EntityState
	19, // 5: wildwood.net.v1.S2C_WorldDelta.player_status:type_name -> wildwood.net.v1.PlayerStatus
	20, // 6: wildwood.net.v1.S2C_WorldDelta.events:type_name -> wildwood.net.v1.WorldEvent
	21, // 7: wildwood.net.v1.S2C_ChatBroadcast.channel:type_name -> wildwood.net.v1.ChatChannel
	22, // 8: wildwood.net.v1.S2C_Error.code:type_name -> wildwood.net.v1.RoomErrorCode
	23, // 9: wildwood.net.v1.S2C_CodexSync.database:type_name -> wildwood.net.v1.CodexEntry
	24, // 10: wildwood.net.v1.S2C_CodexSync.unlocked:type_name -> wildwood.net.v1.CodexUnlock
	24, // 11: wildwood.net.v1.S2C_CodexDelta.unlocked_full:type_name -> wildwood.net.v1.CodexUnlock
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_wildwood_v1_s2c_proto_init() }
func file_wildwood_v1_s2c_proto_init() {
	if File_wildwood_v1_s2c_proto != nil {
		return
	}
	file_wildwood_v1_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_wildwood_v1_s2c_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_HandshakeAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_HeartbeatAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_RoomCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_RoomJoined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_RoomLeft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_PlayerJoined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_PlayerLeft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_RoomKicked); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_RoomStateChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_RoomState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_RoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_WorldDelta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_ChatBroadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_CodexSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wildwood_v1_s2c_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*S2C_CodexDelta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wildwood_v1_s2c_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wildwood_v1_s2c_proto_goTypes,
		DependencyIndexes: file_wildwood_v1_s2c_proto_depIdxs,
		MessageInfos:      file_wildwood_v1_s2c_proto_msgTypes,
	}.Build()
	File_wildwood_v1_s2c_proto = out.File
	file_wildwood_v1_s2c_proto_rawDesc = nil
	file_wildwood_v1_s2c_proto_goTypes = nil
	file_wildwood_v1_s2c_proto_depIdxs = nil
}
