// =====================================================================
// Wildwood 网络协议语义层 — 顶层描述符 (M1.5)
//
// 用 protoc --go_opt=paths=source_relative 编译时,本文件无业务消息,
// 仅作为版本/包元信息的存在。运行时由传输层(M1.9+)按 message type 路由。
//
// 注:本文件有意不 import common.proto / c2s.proto / s2c.proto,
// 仅为让 protoc 不会在 -I 包含整个 v1 目录时产生交叉依赖警告。
// 业务消息见同包 c2s.proto / s2c.proto / common.proto。
// =====================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: wildwood/v1/wildwood.proto

package wildwoodv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 协议元信息(不参与编解码,只用于文档/版本协商)
type ProtocolInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version     string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                               // "1.0.0"
	MaxPlayers  uint32 `protobuf:"varint,2,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`      // 4
	TickRate    uint32 `protobuf:"varint,3,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`            // 20 Hz
	MaxMsgBytes uint32 `protobuf:"varint,4,opt,name=max_msg_bytes,json=maxMsgBytes,proto3" json:"max_msg_bytes,omitempty"` // 4096 (4 KB/tick 预算)
}

func (x *ProtocolInfo) Reset() {
	*x = ProtocolInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wildwood_v1_wildwood_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtocolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolInfo) ProtoMessage() {}

func (x *ProtocolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wildwood_v1_wildwood_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolInfo.ProtoReflect.Descriptor instead.
func (*ProtocolInfo) Descriptor() ([]byte, []int) {
	return file_wildwood_v1_wildwood_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProtocolInfo) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *ProtocolInfo) GetTickRate() uint32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *ProtocolInfo) GetMaxMsgBytes() uint32 {
	if x != nil {
		return x.MaxMsgBytes
	}
	return 0
}

var File_wildwood_v1_wildwood_proto protoreflect.FileDescriptor

var file_wildwood_v1_wildwood_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x69,
	0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x77, 0x69,
	0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x8a, 0x01,
	0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6d,
	0x61, 0x78, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x63,
	0x6b, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x69,
	0x63, 0x6b, 0x52, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x6d, 0x73,
	0x67, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d,
	0x61, 0x78, 0x4d, 0x73, 0x67, 0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f,
	0x64, 0x2f, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x77,
	0x69, 0x6c, 0x64, 0x77, 0x6f, 0x6f, 0x64, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_wildwood_v1_wildwood_proto_rawDescOnce sync.Once
	file_wildwood_v1_wildwood_proto_rawDescData = file_wildwood_v1_wildwood_proto_rawDesc
)

func file_wildwood_v1_wildwood_proto_rawDescGZIP() []byte {
	file_wildwood_v1_wildwood_proto_rawDescOnce.Do(func() {
		file_wildwood_v1_wildwood_proto_rawDescData = protoimpl.X.CompressGZIP(file_wildwood_v1_wildwood_proto_rawDescData)
	})
	return file_wildwood_v1_wildwood_proto_rawDescData
}

var file_wildwood_v1_wildwood_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wildwood_v1_wildwood_proto_goTypes = []any{
	(*ProtocolInfo)(nil), // 0: wildwood.net.v1.ProtocolInfo
}
var file_wildwood_v1_wildwood_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wildwood_v1_wildwood_proto_init() }
func file_wildwood_v1_wildwood_proto_init() {
	if File_wildwood_v1_wildwood_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wildwood_v1_wildwood_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ProtocolInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wildwood_v1_wildwood_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wildwood_v1_wildwood_proto_goTypes,
		DependencyIndexes: file_wildwood_v1_wildwood_proto_depIdxs,
		MessageInfos:      file_wildwood_v1_wildwood_proto_msgTypes,
	}.Build()
	File_wildwood_v1_wildwood_proto = out.File
	file_wildwood_v1_wildwood_proto_rawDesc = nil
	file_wildwood_v1_wildwood_proto_goTypes = nil
	file_wildwood_v1_wildwood_proto_depIdxs = nil
}
